### ISSUE TITLE
This ought to be compatible with vagrant-parallels

### ISSUE THREAD

**Issue by wizonesolutions** [fgrehm/vagrant-cachier#111]
Haven't tested it, but NFS works on it, so no reason it shouldn't be.

[vagrant-parallels](https://github.com/Parallels/vagrant-parallels)

**Comment by bbatsche** [comment]
Done some limited testing, but everything seems to be working great with my Parallels box. Plus, it's *dramatically* faster than this airport's pokey wifi :100:
