### ISSUE TITLE
Disabling a single Bucket

### ISSUE THREAD

**Issue by tknerr** [fgrehm/vagrant-cachier#115]
Is it possible to disable a single bucket?

E.g. to keep `config.cache.auto_detect = true` but disable / blacklist a specific bucket which makes problems?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
