### ISSUE TITLE
Symlink to gem dir instead of ./cache

### ISSUE THREAD

**Issue by hkdobrev** [fgrehm/vagrant-cachier#123]
I (think) have a problem with how this (gorgeous) plugin caches Ruby gems.

Have a look at: https://github.com/fgrehm/vagrant-cachier/blob/b2b0d98dfac02a448c09579edd84e3bd99a8552f/lib/vagrant-cachier/bucket/gem.rb#L14

At the moment it symlinks the gem cache dir `/tmp/vagrant-cache/gem/<ruby version>` to `<gem path>/cache`.

Why not symlink the cache dir directly to `<gem dir>`?

My problem resides in that everything works, but when try to provision offline it doesn't find the gems even if they are previously cached.

Any help is appreciated! Thank you for your work!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
