### ISSUE TITLE
Support to enable setting `/tmp/vagrant-cache` location

### ISSUE THREAD

**Issue by dieend** [fgrehm/vagrant-cachier#126]
I searched the code and found out that location (`/tmp/vagrant-cache`) hardcoded. It should be able to be set up from Vagrantfile. I have problem with `/tmp/` location in vagrant, where it's always unknowingly loss. I usually move every other item that located in `/tmp/` to another location, e.g:       

``` ruby
chef.provisioning_path = "/var/vagrant-chef"
chef.file_cache_path = "/vagrant/.vagrant/file_cache_path"
```

It would be nice if we can set `/tmp/vagrant-cache` to another location.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
