### ISSUE TITLE
Support for caching Docker build data on VM host

### ISSUE THREAD

**Issue by Yserz** [fgrehm/vagrant-cachier#131]
I'm building my Docker containers on my VM host and observed that the docker build data is not cached by the vagrant-cachier plugin. I would really like to see such a feature in the future if this is possible somehow :)

Here's my shortened `Vagrantfile` of my virtual host machine:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  else
    puts 'WARN:  Vagrant-cachier plugin not detected. Continuing unoptimized.'
  end
  ...
  config.vm.define "dev-host" do |host|
    host.vm.hostname = "dev-host"
    host.vm.box = "chef/centos-6.6"
    host.vm.provision "docker" do |d|
      d.build_image "/vagrant/image", args: "-t name/image"
    end
    ...
  end
  ...
end
```

And the `Vagrantfile` of a Docker container:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?('vagrant-cachier')
    puts 'INFO:  Vagrant-cachier plugin detected. Optimizing caches.'
    config.cache.scope = :box
  else
    puts 'WARN:  Vagrant-cachier plugin not detected. Continuing unoptimized.'
  end
  ...
  config.vm.define 'local-workstation' do |ws|
    ...
    ws.vm.provider "docker" do |d|
      d.image = "name/image"
      d.vagrant_machine = "dev-host"
      d.vagrant_vagrantfile = "../Vagrantfile"
      d.has_ssh = true
    end
    ...
  end
end
```

Just to may clearify things an example Output:

```
==> dev-host: Sending build context to Docker daemon 
DEBUG ssh: stdout: Step 0 : FROM centos:centos7

 INFO interface: info: Step 0 : FROM centos:centos7
 INFO interface: info: ==> dev-host: Step 0 : FROM centos:centos7
==> dev-host: Step 0 : FROM centos:centos7
DEBUG ssh: stdout: centos:centos7: The image you are pulling has been verified

 INFO interface: info: centos:centos7: The image you are pulling has been verified
 INFO interface: info: ==> dev-host: centos:centos7: The image you are pulling has been verified
==> dev-host: centos:centos7: The image you are pulling has been verified
DEBUG ssh: Sending SSH keep-alive...
....Downloading....
```

**Comment by fgrehm** [comment]
I guess that this is too much for us to handle from this plugin. I wonder if it would make sense to have that as a separate plugin that builds on top of cachier and trigger plugins... Going to think a bit more on it.

Thanks for all the info so far!

**Comment by ColCh** [comment]
@Yserz :+1: It's working flawlessy on my Windows host
@fgrehm main problem is catch `docker pull` executing

**Comment by ashb** [comment]
I'm not quite sure how we'd tie it in to cachier but the registry image can actually be used as a caching-mirror:

https://github.com/docker/docker/blob/master/docs/sources/articles/registry_mirror.md:

> ## How does it work?
>
>The first time you request an image from your local registry mirror, it pulls the image from the public Docker registry and stores it locally before handing it back to you. On subsequent requests, the local registry mirror is able to serve the image from its own storage.

So maybe the plugin should just configure this registry image to save the images to a cached disk, and then optionally try to configure the docker daemon in the VM?

Thoughts?

**Comment by Yserz** [comment]
It actually already exports every image (downloaded and locally created) on the machine to a cached disk.

**Comment by CharlieC3** [comment]
I'm in a similar situation; we're looking to use Vagrant and Docker to create a local development solution. We need to cache Docker images to reduce the time it takes to run `vagrant destroy; vagrant up` on a project. 

:+1: for Docker support in Cachier.

**Comment by asmaier** [comment]
Another :+1: for docker support in vagrant-cachier

**Comment by majidaldo** [comment]
+1

**Comment by MartinsThiago** [comment]
Hey, based on @Yserz I created a Vagrantfile to cache docker images... now I can use **Fig** and **Docker** for having a full development enviroment. Even on Windows
```
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = 'project'
  config.vm.network "forwarded_port", guest:1521, host:1521
  config.cache.enable :generic, {"docker" => { cache_dir: "/cache-docker" }}

  config.vm.provision "shell", inline: <<-SHELL
    #installs docker
    wget -qO- https://get.docker.io/ubuntu/ | sudo bash

    #installs fig
    wget -qO- https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /usr/local/bin/fig
    chmod +x /usr/local/bin/fig

  	#load cached images
  	docker load -i /cache-docker/*.tar

  	#run your commands
    fig -f /vagrant/fig.yml up

  	#cache your images
  	IMAGES=`docker images | awk '{print $1}' | tail -n +2`
  	docker save -o /cache-docker/images.tar $(echo ${IMAGES[@]})
  SHELL

  config.vm.provision "shell", run: "always", inline: "fig -f /vagrant/fig.yml up"

end
```

**Comment by leighmcculloch** [comment]
@MartinsThiago your save and load works good, I'm using it, but I've altered the save command to exclude images with the name `<none>` since they're old and I likely don't need them. The existing command error'd on them.

```bash
IMAGES=`docker images | awk '{print $1}' | grep -v '<none>' | tail -n +2`
docker save -o /docker-cache/images.tar $(echo ${IMAGES[@]})"
```

**Comment by MartinsThiago** [comment]
Nice @leighmcculloch, I actually dropped its usage for now :(... I tried to work with some usual containers like postgres and mongo... but there's too much data to be downloaded :(

Something around **3GB**... waiting for the day we could use a git aproach like `git clone --depth 1`

**Comment by amcorreia** [comment]
Maybe an option for docker is just use another container with apt-cacher like this https://registry.hub.docker.com/u/sameersbn/apt-cacher-ng/

**Comment by patcon** [comment]
cc: @mrjcleaver

**Comment by rmohr** [comment]
A nice solution @fabiand  came up with in our use case, is to use an extra disk as docker storage location.
He put  this in our deployment script:
```bash
 # if there is a second disk, use it for docker
 if ls /dev/*db ; then
 # We use the loopback docker dm support, and not a VG for now
   mkdir -p /var/lib/docker/
   restorecon -r /var/lib/docker
   mount LABEL=dockerdata /var/lib/docker/ || {
     mkfs.xfs -L dockerdata -f /dev/?db
   }
mkdir -p /etc/systemd/system/docker.service.d/
cat > /etc/systemd/system/docker.service.d/mount.conf <<EOT
 [Service]
 ExecStartPre=/usr/bin/sleep 5
 ExecStartPre=-/usr/bin/mount LABEL=dockerdata /var/lib/docker
 MountFlags=shared
 EOT
   mount LABEL=dockerdata /var/lib/docker/
 fi
```

Then I just had to add an additional disk to the Vagrant VM which would survive `vagrant destroy`.
```ruby
# for vagrant-libvirt provider
 if $cache_docker then
     domain.storage :file, :size => '10G', :path => 'master_docker.img', :allow_existing => true
end
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
