### ISSUE TITLE
Cachier does not resolve provisioners with Vagrant 1.7.1

### ISSUE THREAD

**Issue by Yserz** [fgrehm/vagrant-cachier#133]
Due to a modification in Vagrant 1.7.1 or earlier cachier does not resolve provisioners correctly anymore. Thus for example the chef caching is broken.

The bug applies for example here:
https://github.com/fgrehm/vagrant-cachier/blob/master/lib/vagrant-cachier/cap/linux/chef_file_cache_path.rb

The vagrant-butcher plugin created by @cassianoleal already solved this bug here:
https://github.com/cassianoleal/vagrant-butcher/commit/81cc73c02f17af272a870bce02ff287190768a51

**Comment by tknerr** [comment]
See also: 
https://github.com/mitchellh/vagrant/issues/5069
