### ISSUE TITLE
json 1.8.2 does not seam to be installing when installing your plugin 

### ISSUE THREAD

**Issue by athingisathing** [fgrehm/vagrant-cachier#136]
I get an error when installing json 1.8.2 while it installs your plugin.

Please let me know what else you need

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
