### ISSUE TITLE
Generic bucket error

### ISSUE THREAD

**Issue by hpatoio** [fgrehm/vagrant-cachier#138]
I'm trying to setup a generic bucket. Here my `Vagrantfile`

```
config.vm.synced_folder "/var/www/myapp/", "/var/www/myapp/", :nfs => true

if Vagrant.has_plugin?("vagrant-cachier")
  config.cache.scope = :machine

  config.cache.synced_folder_opts = {
    type: :nfs,
    mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  }

  config.cache.enable :generic, {
    "cache"  => { cache_dir: "/var/www/myapp/app/cache" },
    "logs"   => { cache_dir: "/var/www/myapp/app/logs" },
    "vendor" => { cache_dir: "/var/www/myapp/vendor" },
  }
end
```

In the guest machine I see 

```
/var/www/myapp/vendor -> /tmp/vagrant-cache/vendor
/var/www/myapp/app/logs -> /tmp/vagrant-cache/logs
/var/www/myapp/app/cache -> /tmp/vagrant-cache/cache
```

And the directories have the file from the host machine. In the host machine I can see the symlinks but they all point to non existing directories under `/tmp/vagrant-cache`

Host machine is `Ubuntu 13.04` - Guest machine `Ubuntu  14.04`

What's wrong ?

**Comment by fgrehm** [comment]
Dunno, the only thing that occurs to me right now is that it might be that NFS can't handle nesting of subdirectories? Try using `cache_dir`s outside of the main `/var/www/myapp` and let us know if it works!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
