### ISSUE TITLE
Add Integration with Platformio

### ISSUE THREAD

**Issue by dannystaple** [fgrehm/vagrant-cachier#140]
Platformio is a system for setting up build environments for embedded development. 

It downloads a load of stuff - compilers, libraries, uploaders and so on. 

When vargant up'ing and destroying one of these, it is downloading all it's parts again. It uses pip, and wget (which can be integrated), but also uses python urllib2 and other mechanisms to download.

**Comment by fgrehm** [comment]
The "How to create a new bucket?" section from [docs](http://fgrehm.viewdocs.io/vagrant-cachier/development) should give you a head start in case you want to contribute (doesn't mean that you'd have to send a PR, but I have no experience with Platform.io and I don't even know where to start :grin: )

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
