### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-cachier#143]
Hey guys!

Life, as it tends to do, has progressed for me in such a way that I am no longer able to devote time to maintaining this plugin, especially as I no longer use it on a daily basis.

As such, this project has been neglected and I apologize for that. I am hoping there is someone who would be willing to step up and take over maintaining this project so it gets the attention it deserves. If you would like to do so, please respond with a comment explaining a bit about what you would like to do as a maintainer of this project. I'll then add one or more of those users as collaborators.

Thanks everyone!

**Comment by aneeshusa** [comment]
I just started using vagrant-cachier a few days ago, but I'd be willing to maintain this project. It definitely solves one of my pain points and I see myself using it for a long time. I'd want to start with triaging the existing issue list and shoring up the test suite, then look at adding new bucket types. FYI, I'm in the middle of finals right now so I'll be busy for another week and a half, but after that I'll be able to pick up the pace. Also, huge shoutout for making this plugin - it saves me a ton of time, and I really appreciate the effort you've put in.

**Comment by fgrehm** [comment]
@aneeshusa Awesome! I went ahead and added you as a collaborator on the project, enjoy your superpowers :dancer:

LMK when you are ready to cut a release and I'll look into setting things up on the RubyGems side of things. If you need any feedback or help feel free to ping me here, I wont be able to help out testing / writing code but I'm always available to answer questions you and other collaborators might have.

Cheers! :beers:

**Comment by rogeriopradoj** [comment]
:+1: good luck!

**Comment by cromulus** [comment]
Congrats!

This is an important project and I'm happy to see someone step up!

**Comment by aneeshusa** [comment]
Thanks for the kind words everyone! Pushing through finals right now but looking forward to getting started on maintaining next week.

**Comment by jalcine** [comment]
Is there a label to look into for helping out?

**Comment by schlueter** [comment]
I'd be willing to assist as well if you'd like help @aneeshusa .

**Comment by fgrehm** [comment]
@jalcine @schlueter any kind of help would be greatly appreciated, be it triaging issues, fixing bugs, testing PRs.... I'm up for providing commit access to the repository but given the current project activity and the amount of collaborators we have from the time I put together the [PR Hack](https://github.com/fgrehm/vagrant-cachier/issues/10) I'd like to see some action first.

For now I'm going to start fresh and will clean up the write access we have around besides @patcon's since he helped out with the latest release 

_Sorry @mindreframer @cromulus @fh @laggyluke @tmatilai @gimler @aneeshusa, I can get you write access again in case you guys are interested, feel free to unwatch this issue and avoid getting additional noise on your inboxes and thanks for the help you provided!_

**Comment by joelhandwell** [comment]
@aneeshusa Is there any updates?

**Comment by lwh** [comment]
Do you still need people?

**Comment by fgrehm** [comment]
Yes!

**Comment by rmohr** [comment]
Hi Fabio,

I would also be very interested in helping out. As a start I would want to merge #180 to make the plugin work properly on newer Fedora guests.

**Comment by fgrehm** [comment]
Damn, I'm really sorry @rmohr, your email got "lost" in my inbox. You should receive an invite for collaborating on the project any time soon so you got the power now!

LMK when you are ready to cut a release and shoot me you rubygems account.

**Comment by amontalban** [comment]
Hi @fgrehm,

Do you need more help? I want #168 to be merged but nobody took it in almost a year.

Thanks!

**Comment by rmohr** [comment]
@amontalban will look at it tomorrow, @fgrehm since my time is also very limited I would be happy to have @amontalban as maintainer too.

**Comment by deiga** [comment]
@rmohr @fgrehm What is the status here currently? Can I help with stuff? :)

**Comment by patcon** [comment]
Having recently gone through a successful effort in transferring maintainership, I'd say that creating a gitter.im chat room and submitting a PR for the README badge is a great way to start. It makes it easy to invite in potential maintainers, have some lightweight convos about style and process and triage, and get a repo moving again :)

**Comment by tarcinil** [comment]
I would be interested in helping with this effort.  I would look at adding Travis testing as well as DCO for all pull requests.

**Comment by davividal** [comment]
@rmohr @patcon @fgrehm @amontalban what is the current status?
How can I help?
I noticed that the gitter.im/fgrehm/vagrant-cachier is pretty much dead.

**Comment by Dispader** [comment]
I'll also say-hey, here: the Cachier plugin is important enough to our CI efforts, and I've run an open source project or two over the years.  We might-could form a team: I'm wagering the work is pretty light, here.

**Comment by patcon** [comment]
Sorry, never did get push access myself to pass along. But I support these offers! So long as you're not overzealous about blockchain tech... ;)

(See also: event-stream)

**Comment by davividal** [comment]
@Dispader and @patcon : I forked this repo and gave you both access to it.
Let's get it moving :)

**Comment by patcon** [comment]
Thanks! I'm not using this anymore, but I'll ping Fabio on the Twitters about delegating push to y'all (and me if I can help in situations like this in future)

**Comment by fgrehm** [comment]
hey peeps! sorry for the silence here. if you guys are able to create a github org and give me enough 💪 I can transfer ownership to the org right away. I can also give away rubygems push permissions to people but I'd rather give it to just one person that is capable of setting up gem releases from CI

Cheers!

**Comment by Tcharl** [comment]
I Have a github org related to ansible, vagrant, packer and stuff: https://github.com/OsgiliathEnterprise, 

I can invite the maintainers and you @fgrehm so that someone can takeover the plugin (I would be very happy to see dnf support published :-)).

Are you interested ladies and gentlemen?

**Comment by b-long** [comment]
Just commenting to say that I hope the maintainer search is a success and this plugin lives on!  Perhaps some of the (previous) volunteers could be elevated to review pull requests & issues in this repository?

**Comment by tknerr** [comment]
Side note: I just figured out there are some worthy updates in master (such as support caching `:pip` packages) which have never made it into a release, and probably many people who still use vagrant-cachier by today would benefit from that.

Would it be possible to get a new version of vagrant cachier released and pushed to rubygems.org?
