### ISSUE TITLE
Does not seem to work on Ubuntu 15.04 host with VirtualBox and NFS shared folders

### ISSUE THREAD

**Issue by edmundcraske** [fgrehm/vagrant-cachier#146]
We've got a development environment set up which enables NFS shared folders. We've not noticed any particular issues with it (vagrant-cachier gets installed by a script if it is missing so everyone is using it in this way) across a variety of distributions, but have found a recreatable issue with Ubuntu 15.04 that seems to prevent yum from working on a CentOS 6.5 guest.

I'm not really sure where to look to pinpoint the cause of this issue.

**Comment by fgrehm** [comment]
Sorry but I don't have enough cycles to test this now so [any type of help would be greatly appreciated](https://github.com/fgrehm/vagrant-cachier/issues/143)!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
