### ISSUE TITLE
Creating support for windows

### ISSUE THREAD

**Issue by jmahowald** [fgrehm/vagrant-cachier#147]
We were just having an internal discussion about caching for windows in test kitchen, and people were talking about local proxy servers, etc.  I don't know if it's feasible, but if we got lucky and got @mwrock or some other windows experts to chime in, we might be able to design that addition

**Comment by fgrehm** [comment]
:+1: but [help will be needed](https://github.com/fgrehm/vagrant-cachier/issues/143)

**Comment by mwrock** [comment]
Huge +1 for windows support. We use this plugin and it is awesome on my linux laptop and whenever i use my [chef workstation](https://github.com/mwrock/chef_workstation) on windows i miss it. I'm unsure how much I can contribute. Desire is high, but time...alas...not so much.

**Comment by raeesiqbal** [comment]
bump!!

**Comment by kaltokri** [comment]
+1. I'm missing it painfully since we use Windows 10 base box. :)

**Comment by tknerr** [comment]
+1

see also #137

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
