### ISSUE TITLE
Permission denied in .npm directory

### ISSUE THREAD

**Issue by inancgumus** [fgrehm/vagrant-cachier#148]
When I run: `vagrant provision --provision-with test` I got these errors. Provision script is in bash and empty just for testing. Before these errors I had installed some npm packages via another bash provision script.

When I ssh'ed into the machine and typed `sudo chown -Rf vagrant:vagrant ~/.npm` the error disappears.

I have version vagrant-cachier 1.2.0

[Standard output](https://gist.github.com/deeperx/537892bf925472d52d92)
[Debug output](https://gist.github.com/deeperx/711447c82bfb00cf43ad)

_PS: This looks like a kind of the same problem just like in here: https://github.com/fgrehm/vagrant-cachier/issues/74#issuecomment-106058094_

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
