### ISSUE TITLE
Mistakenly made small change directly on master from web UI :/

### ISSUE THREAD

**Issue by patcon** [fgrehm/vagrant-cachier#149]
Ack. Grrr... Sorry guys. I forgot a had push access here, and was thinking I was submitting a simple change via PR in the web UI :/

https://github.com/fgrehm/vagrant-cachier/commit/dd32f2472e60af948d2c36033b122acd7065f9f3

Should I revert and resubmit in a PR, or is this small enough to leave it, despite the *faux pas*?

**Comment by fgrehm** [comment]
I'm cool with keeping it around but since I'm not actively using the plugin I'd recommend trying to get someone else to try it out before :ship: ing it! :smile:

**Comment by patcon** [comment]
:+1: Thanks fabio :)

**Comment by patcon** [comment]
Despite my "oops I fucked up", would you be comfortable giving me rubygems access to a can push out a new release?

**Comment by fgrehm** [comment]
:shipit:
