### ISSUE TITLE
Support for Vagrant's built-in chef installer

### ISSUE THREAD

**Issue by patcon** [fgrehm/vagrant-cachier#150]
An installer is currently built right into the default chef provisioners, so it seems `vagrant-omnibus` is now only required for advanced usage (if at all).

https://docs.vagrantup.com/v2/provisioning/chef_common.html

Would be great to set the default `chef.installer_download_path` to the one we already use for vagrant-omnibus. For now, I'm just manually setting it to use chef's `file_cache_path`, which already has a bucket when chef provisioners are used.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
