### ISSUE TITLE
Disabling vagrant-cachier leaves a symlink around

### ISSUE THREAD

**Issue by kutschkem** [fgrehm/vagrant-cachier#152]
I had to disable vagrant-cachier because of #117, this left the yum-cache as a symlink in my VM. Would it be possible for the plugin to "clean up after itself"?

Leaving the symlink leads to 'No such file or directory' errors.

I am unaware of the plugin architecture, but I suppose this means checking for things even when the plugin is not used. Maybe a small file on the guest could help to see which caches were configured in the last run, and this could be matched against the current configuration.

**Comment by benhosmer** [comment]
This might be implemented already:

```
==> default: Removing cache buckets symlinks...
==> default: Attempting graceful shutdown of VM...
==> default: Destroying VM and associated drives...
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
