### ISSUE TITLE
support gem/npm offline installation

### ISSUE THREAD

**Issue by everflux** [fgrehm/vagrant-cachier#157]
The caching of the apt-lists works great, it would be wonderful of the npm and gem lists could be cached as well to support complete offline installation of a box.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
