### ISSUE TITLE
Feature req (simple): set config.cache.scope to ANY host directory.

### ISSUE THREAD

**Issue by Techienaut** [fgrehm/vagrant-cachier#160]
Hi! Simple request. I want to be able to set cache location to ANY directory besides :box or :machine. So a simple string (e.g. config.cache.scope = "~/OneDrive/Developer/vagrant_apt_cache"). 

Also thank you for this plugin!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
