### ISSUE TITLE
NFS shared folder timed out

### ISSUE THREAD

**Issue by raupie** [fgrehm/vagrant-cachier#166]
Trying the nfs options (mount_options: ['rw', 'vers=3', 'tcp', 'nolock']) and the provisioning hangs for 15 minutes then fails with a timed out error. 

I'm running windows 7 and have winnfsd set up for my shared folders.

**Comment by czerasz** [comment]
I have the same issue on Ubuntu `16.04`

**Comment by raupie** [comment]
Removing the `synced_folder_opts` section allows the box to load now. I was trying to use `vagrant-cachier` for symfony / ezpublish `cache`, `log` and `vendor` folders. 

    config.cache.enable :generic, {  
      "cache"  => { cache_dir: "/var/www/symfony.dev/public_html/app/cache" },
      "logs"   => { cache_dir: "/var/www/symfony.dev/public_html/app/logs" },
      "vendor" => { cache_dir: "/var/www/symfony.dev/public_html/vendor" },
    }

It appears to be working. I can see those cache buckets are now symlinks. Not sure if I should see anything in my `C:\Users\USERNAME\.vagrant.d\cache\VENDOR\BOX` folder.

Thank you for your help.
