### ISSUE TITLE
Two chef_solos gives `One machine is using multiple chef provisioners, which is unsupported.`

### ISSUE THREAD

**Issue by poflynn** [fgrehm/vagrant-cachier#172]
My Vagrantfile looks something like this:

```
config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "niceRecipe1"
    chef.add_recipe "niceRecipe2"
end

config.vm.provision :shell, :path => "uglyScript1.sh"
config.vm.provision :shell, :path => "uglyScript2.sh"

config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "niceRecipe1"
    chef.add_recipe "niceRecipe2"
end
```

I.e. a chef_solo section, a bunch of shell scripts and another chef_solo section. It all worked great until I added the second chef_solo section, now I get:

`One machine is using multiple chef provisioners, which is unsupported.`

Note that I am not mixing chef_client and chef_zero or anything of that nature, merely adding another chef_solo. Is that really unsupported?

Thanks.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
