### ISSUE TITLE
"Problem unlinking the file" issue

### ISSUE THREAD

**Issue by AlexeyKosov** [fgrehm/vagrant-cachier#176]
After each "apt-get install" I see a lot of warnings like these:

```
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.gJZOnb - IsAccessibleBySandboxUser (26: Text file busy)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.42ZQeh - IsAccessibleBySandboxUser (26: Text file busy)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.n4m55m - IsAccessibleBySandboxUser (26: Text file busy)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.zf5uXs - IsAccessibleBySandboxUser (26: Text file busy)
W: Problem unlinking the file /var/cache/apt/archives/partial/.apt-acquire-privs-test.yQb7Oy - IsAccessibleBySandboxUser (26: Text file busy)
```

Host OS: Windows 8.1
Guest OS: Ubuntu 16.04
Vagrant: 1.8.1 
VirtualBox: 5.0.16

Cachier config:

```
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
```

**Comment by giankdm** [comment]
Mine is similar, vagrant on OSX accesses Linux, during vagrant halt it says

unlink: cannot unlink ‘/var/cache/apt/archives’: Read-only file system

**Comment by tknerr** [comment]
Same as @AlexeyKosov here. Wondering if we can tell cachier to ignore the whole `/var/cache/apt/archives/partial/` directory?

**Comment by dheeraj141** [comment]
sudo reboot will solve the issue

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
