### ISSUE TITLE
Add option to the generic bucket to be global

### ISSUE THREAD

**Issue by QuingKhaos** [fgrehm/vagrant-cachier#178]
It would be useful to create buckets where the scope can be global and not box or machine like for the rest.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
