### ISSUE TITLE
Does not create pip bucket if pip is explicitly enabled but pip isn't yet installed.

### ISSUE THREAD

**Issue by SteveAyre** [fgrehm/vagrant-cachier#179]
The pip support checks whether pip is installed (runs 'which pip'), and does not create the pip bucket if pip is not yet found. However this means that when using a bootstrap script that installs pip and then installs a requirements file then those pip requirements will never use the cache. As a workaround pip has to be installed in a separate bootstrap script first.

This might make some sense in the 'autodetect' mode, but if the pip bucket is explicitly enabled (config.cache.enable :pip) it might make more sense to avoid the 'which pip' test and always create the bucket.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
