### ISSUE TITLE
Issue with cachier and Ubuntu 16.04

### ISSUE THREAD

**Issue by kiklop74** [fgrehm/vagrant-cachier#182]
I am currently experimenting with vagrant and Ubuntu 16.04 64bit using bento/ubuntu-16.04. While performing tests that included vagrant-cachier I noticed unfortunate behavior.

In order to provide cached packages cachier creates a temporary directory that points within the VM os to /tmp/vagrant-cache/apt/ and is symlinked to /var/cache/apt/archives/ . All nice and neat except one thing. The directory /tmp/vagrant-cache/apt/ is created and owned by the user vagrant. That in turn generated following warning message when installing any package using apt-get.

```
sudo apt-get install libjs-jquery-lazyload

Reading package lists... Done
<snipped extra stuff>

W: Can't drop privileges for downloading as file '/var/cache/apt/archives/partial/libjs-jquery_1.11.3+dfsg-4_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

**Comment by scanepa** [comment]
Adding the following lines in your config should to the trick:
```
 config.cache.synced_folder_opts = {
      owner: "_apt",
      group: "_apt"
    }
```
I'm thinking the right solution is create another synced folder.

**Comment by keengene** [comment]
Had the same problem. This did it for me:

config.cache.synced_folder_opts = {
      owner: "_apt",
      group: "vagrant"
    }

**Comment by kiklop74** [comment]
Thanks
