### ISSUE TITLE
Allow caching directory to be moved around on host system

### ISSUE THREAD

**Issue by avinash-oza** [fgrehm/vagrant-cachier#183]
Hi,

I am really enjoying this plugin so far. However, my home directory is encrypted causing issues with the NFS mounting. I have taken a look here and seen its something not supported [here](https://serverfault.com/questions/409639/nfs-with-encrypted-ubuntu-home-directory). 

My idea is to add another configuration attribute specifying the root to be used for caching. If this is specified, it overrides checking the `:machine` or  `:box` specification and builds the root at that spot.

Apologies if this is not the correct way to propose ideas, etc. My first time attempting to contribute :smile:

**Comment by skylord123** [comment]
Just ran into this issue as well.

**Comment by avinash-oza** [comment]
@skylord123 : I made an attempt to redirect the directory used as the root for the packages. Feel free to checkout my branch here: https://github.com/avinash-oza/vagrant-cachier/tree/override_host_directory

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
