### ISSUE TITLE
Ubuntu failure with 

### ISSUE THREAD

**Issue by chrisvire** [fgrehm/vagrant-cachier#185]
I am using:
VirtualBox 5.1.28
Vagrant 2.0.0 with vagrant-cachier 1.2.1
VM: Ubuntu 16.04 (chrisvire/xenial64) 
Host: iMac (macOS 10.12.6)

When I use apt commands (e.g. "sudo apt update"), I get the following error:

W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Hmm... I just tried it on my Linux Desktop as host (16.04) and I am getting a similar error:

W: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_xenial_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by thorr18** [comment]
The fix for me was to change the Vagrantfile to use _apt as the owner instead of vagrant: 

```
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
       owner: "_apt",
    }
  end
```
Vagrant 2.0.1
Base Box: "bento/ubuntu-16.10"
Plugins: 
vagrant-cachier (1.2.1)
vagrant-share (1.1.9, system)
virtualbox (0.8.6)

Error: 
>     default: Running: inline script
>     default: W
>     default: : 
>     default: Can't drop privileges for downloading as file '/var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_yakkety_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
>     default: Reading package lists...

**Comment by thorr18** [comment]
Found duplicate #175

**Comment by groovenectar** [comment]
I have been running into this every time now...

```
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: chown to _apt:root of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_InRelease failed - Item::QueueURI (1: Operation not permitted)
W: chown to root:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_InRelease failed - 201::URIDone (1: Operation not permitted)
W: chown to _apt:root of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_InRelease failed - Item::QueueURI (1: Operation not permitted)
W: chown to root:root of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_bionic-security_InRelease failed - 201::URIDone (1: Operation not permitted)
W: chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-updates_InRelease failed - Item::QueueURI (1: Operation not permitted)
W: chown to root:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-updates_InRelease failed - 201::URIDone (1: Operation not permitted)
W: chown to _apt:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-backports_InRelease failed - Item::QueueURI (1: Operation not permitted)
W: chown to root:root of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-backports_InRelease failed - 201::URIDone (1: Operation not permitted)
```

I tried uninstalling and reinstalling all the plugins, like someone suggested in #175.

Also tried `config.cache.synced_folder_opts`, I don't think that worked, but even if it does... that would change the user/group of Vagrant's mounted files to `_apt`.... probably not the desired scenario?

Upgraded to latest Vagrant and latest VirtualBox 5.2. I've got no idea what could be causing it. so far the only solution is to not use `vagrant-cachier`, but I would like to be using it

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
