### ISSUE TITLE
Document Config Variables

### ISSUE THREAD

**Issue by jamiejackson** [fgrehm/vagrant-cachier#187]
How do you disable the plugin for a given machine/`Vagrantfile`? It's discussed [here](https://github.com/fgrehm/vagrant-cachier/issues/72), but never documented, AFAICT.

Also, how does `cache.enable_nfs` work? I see it mentioned [here](https://github.com/fgrehm/vagrant-cachier/issues/69#issuecomment-30530753), but I don't see it documented.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
