### ISSUE TITLE
Version on rubygems is not the same as version on github, yet version numbers are the same?

### ISSUE THREAD

**Issue by najamelan** [fgrehm/vagrant-cachier#190]
Notably bucket/dnf.rb and bucket/pip.rb are missing on rubygems. Other files that have changed are bucket/yum.rb, bucket.rb, ...

Both have version set to 1.2.1

What's going on?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
