### ISSUE TITLE
opaque error message: "cannot load such file -- cachier"

### ISSUE THREAD

**Issue by brainchild0** [fgrehm/vagrant-cachier#191]
I am unable to operate Vagrance after installing the plugin, always receiving a particular error message, which I am not able to interpret.

The host is Linux Mint 20.3. Vagrant was installed from the vendor's Debian repository.

Following is the output, and the commands that produce it:

```
$ vagrant plugin  install cachier
Installing the 'cachier' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Fetching cachier-0.0.1.gem
Installed the plugin 'cachier (0.0.1)'!
```
```
$ vagrant up --provider=libvirt
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- cachier
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
