### ISSUE TITLE
overriding method for synced folders

### ISSUE THREAD

**Issue by brainchild0** [fgrehm/vagrant-cachier#192]
Is support available for overriding the default method for synced folders?

I apologize if the matter is documented, but I have not found any clear answer in the documentation. It seems to be assumed that the method for syncing folders would be the   the one that is default for the provider, but such  may not be possible in all cases.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
