### ISSUE TITLE
Intelligently handle conflict of having chef lockfile in NFS mount of file_cache_path

### ISSUE THREAD

**Issue by patcon** [fgrehm/vagrant-cachier#28]
- can now cache `Chef::Config['file_cache_path']` [GH-14]
- cache share can be an NFS mount [GH-7]

However, chef-solo and chef-client both drop their lockfiles in `file_cache_path`, and it's not recommended that the lockfile be places on NF mounts:
http://docs.opscode.com/config_rb_solo.html

See the "Run Locking" section of this post:
http://www.opscode.com/blog/2013/02/06/chef-11-in-depth-client-improvements/

> Note that the locking mechanism uses flock. This means that if Chef dies unexpectedly, the lock will automatically be released, so you don’t need to deal with stale lockfiles blocking Chef runs. **By default, the lockfile is located at `$file_cache_path/chef-client-running.pid`. Some filesystems (most notably NFS) don’t support flock,** so you’ll need to manually configure the lockfile location if you’re using such a filesystem.

Hasn't been an issue yet, so not urgent, but might surface later. The plugin should perhaps override the `lockfile` setting and place it in `/tmp`, perhaps if it detects NFS shares are enabled for the cache dir, or perhaps regardless.

This is blocked by the fact that Vagrant core templates don't allow `lockfile` to be configured in `solo.rb` and `client.rb`:
https://github.com/mitchellh/vagrant/tree/master/templates/provisioners

**Comment by tknerr** [comment]
Should be easy to add a `lockfile` chef config option to vagrant core (as a prerequisite before setting this value properly in vagrant-cachier).

Would have to be added in a few places only (e.g. compare with `file_cache_path`):
https://github.com/mitchellh/vagrant/search?utf8=%E2%9C%93&q=file_cache_path

Maybe I can whip something up before vagrant 1.8 comes out... (but on the other hand it seems not really required as a custom config file can be provided by now already - it's just a bit more tedious...)

**Comment by fgrehm** [comment]
Cool, LMK if that works out and I can give you the permissions for cutting a new release :)

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
