### ISSUE TITLE
Add cache "buckets" for maven

### ISSUE THREAD

**Issue by nikolauskrismer** [fgrehm/vagrant-cachier#57]
Would it be possible to add cache "buckets" for maven?
If one installs maven using yum, the packages from the local maven repository should also get cached

**Comment by gildegoma** [comment]
Hi! is there anybody working on this at the moment?

**Comment by fgrehm** [comment]
Not me! :P

**Comment by sworisbreathing** [comment]
@typekpb @gildegoma have you tried @hardyoyo's solution?

```ruby
...

# use the generic cache bucket for Maven
config.cache.enable :generic, {
  "maven" => { cache_dir: "/home/vagrant/.m2/repository" }
}
...
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-cachier/issues/193, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
