### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by purpleidea** [fgrehm/vagrant-cachier#74]
Occasionally when running provision (usually an initial provision has already happened)

```
[machine1] Rsyncing folder: /home/user/vagrant/foo/ => /vagrant
[machine1] Configuring cache buckets...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p /tmp/vagrant-cache/yum

Stdout from the command:

Stderr from the command:

mkdir: cannot create directory `/tmp/vagrant-cache': Permission denied
```

This is using vagrant on F19, with vagrant-libvirt.
Setup described here:
https://ttboj.wordpress.com/2013/12/09/vagrant-on-fedora-with-libvirt/
and here:
https://ttboj.wordpress.com/2013/12/21/vagrant-vsftp-and-other-tricks/

Cheers

**Comment by deeperx** [comment]
@fgrehm I have kind of the same problem I guess. I have version vagrant-cachier 1.2.0

[Standard output](https://gist.github.com/deeperx/537892bf925472d52d92)
[Debug output](https://gist.github.com/deeperx/711447c82bfb00cf43ad)

When I run: ```vagrant provision --provision-with test``` I got these errors. Provision script is in bash and empty for just testing.

**Comment by fgrehm** [comment]
Sorry but [I won't be able to help you ATM](https://github.com/fgrehm/vagrant-cachier/issues/143) =/

Do you mind opening up another issue so that other people can chime in? I'd reopen this one but it is way too big already

**Comment by deeperx** [comment]
OK @fgrehm I've opened a new issue [here](https://github.com/fgrehm/vagrant-cachier/issues/148), cheers
