### ISSUE TITLE
Support for caching python modules

### ISSUE THREAD

**Issue by scottmuc** [fgrehm/vagrant-cachier#80]
I'm a bit of a newb when it comes to python packaging so I don't know the details. Like rubygems, pip is used to install packages from remote repositories.

**Comment by white-hat** [comment]
Hi!
AFAIK pypa/pip#1969 is fixed in pip 6.1
I'd love to have a working pypi bucket :)

**Comment by fgrehm** [comment]
Awesome! I've been MIA for a while down here and would love to have more contributors around to keep the fire burning. I'd be more than happy to provide write access to this repo to whoever gets to implement this.

Cheers
